name: MCBackup-KeepAlive
on:
  schedule:
    - cron: '0 2 * * *'   # 9h sáng VN
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: install rclone & sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone sshpass
      - name: create rclone.conf
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          [sftp]
          type = sftp
          host = ${{ secrets.SFTP_HOST }}
          port = ${{ secrets.SFTP_PORT }}
          user = ${{ secrets.SFTP_USER }}
          pass = $(rclone obscure "(khang@@@2011)")
          [gdrive]
          type = drive
          scope = drive
          token = {"access_token":"ya29.a0AUMWg_Jipx_NwWmXs_g1HR8Qm1Xqtch4RCDADei6QXZdqHMnYpgo3OHGetDbfI64oSRu_rdquMrKhVkN-NGwJK8zAsx9sdEZIKERIRm_PE1lAUwWnZBRBLQYyK0MoFJ444XZwzGx4zw51qESRaqi7D88drZu-izvBH1WhYpBYQI-NN4F4hKp-4t8dT9qTizjF-B8EL4aCgYKAYoSARMSFQHGX2MiwjvqsebzV92oCpKL8-Cy5w0206","token_type":"Bearer","refresh_token":"1//0eoZ6M4h3RcGxCgYIARAAGA4SNwF-L9IrvNFqFVoZkPl7tWpvryggYl2E2cMx981n4ecUZckce-KAorLkcSRWhzn1kf6xgRAfJc4","expiry":"2026-01-17T13:41:37.0212493+07:00","expires_in":3599}
          EOF
      - name: backup worlds → Drive
        run: |
          DATE=$(date +%F-%H%M)
          rclone copy sftp:worlds gdrive:mc_backup/$DATE -v --transfers=2
      - name: keep-alive file
        run: |
          echo "$(date) keep-alive" | rclone rcat sftp:keep-alive.txt -v
      - name: delete old backups (keep 10 GB)
        run: |
          rclone delete gdrive:mc_backup --drive-use-trash=false --max-size 9G
